const events = [
  {
    id: '1',
    Title: 'Soccer Tournament',
    Description: 'A friendly soccer tournament',
    Date: '2023-10-20',
    startTime: '10:00 AM',
    endTime: '10:50 AM',
    IsRecurring: true,
    UserID: '1',
    CategoryID: 'Daily',
  },
  {
    id: '2',
    Title: 'weekly sync',
    Description: 'synchronization of what you learned with buddy',
    Date: '2023-10-21',
    startTime: '1:00 PM',
    endTime: '2:50 PM',
    UserID: '1',
    IsRecurring: true,
    CategoryID: 'Weekly',
  },
  {
    id: '3',
    Title: 'Business webinar',
    Description: 'Business meeting',
    Date: '2023-11-25',
    startTime: '1:00 PM',
    endTime: '2:50 PM',
    IsRecurring: true,
    UserID: '1',
    CategoryID: 'Monthly',
  },
  ,
  {
    id: '4',
    Title: 'DSL',
    Description: 'synchronization of what you learned with buddy',
    Date: '2023-12-26',
    startTime: '1:00 PM',
    endTime: '2:50 PM',
    UserID: '2',
    IsRecurring: true,
    CategoryID: 'Weekly',
  },
  {
    id: 'PSL',
    Title: 'Business webinar',
    Description: 'Business meeting',
    Date: '2023-12-27',
    startTime: '1:00 PM',
    endTime: '2:50 PM',
    IsRecurring: true,
    UserID: '1',
    CategoryID: 'Monthly',
  },
];

export default events;
